### ISSUE TITLE
Thanks for your work 

### ISSUE THREAD

**Issue by Devba** [piWallet/piWallet#4]
Hey @johnathanmartin

I'm using your wallet and wanted to than you for your work 

Please have 3$ on  @ChangeTip.

**Comment by johnathanmartin** [comment]
I am more than happy to help you. I would love to see your wallet too if that's okay. If you ever have any questions or problems feel free to message me.

I'm afraid the tip didn't go through though. This may be because its under @piWallet instead of @johnathanmartin.

**Comment by Devba** [comment]
Thanks Johnatan 

I have sent it  to the donation address instead:
Transaction : 776916a62cfcb4d9a3a350ea27e611700bc1d9b1f5a59e01b8f84d5740dbd36c

I just forked it to  
https://github.com/Devba/UniWallet

Created a countdown for withdraws and a few other small changes 

Thanks again for your work
